-- ACCOUNT data
INSERT INTO "ACCOUNT" (ACCOUNT_ID, ACCOUNT_NUMBER, BALANCE) VALUES (1, '111111', 100000);
INSERT INTO "ACCOUNT" (ACCOUNT_ID, ACCOUNT_NUMBER, BALANCE) VALUES (2, '222222', 200000);
INSERT INTO "ACCOUNT" (ACCOUNT_ID, ACCOUNT_NUMBER, BALANCE) VALUES (3, '333333', 300000);

-- TRANSACTION data
INSERT INTO "TRANSACTION" (TRANSACTION_ID, TRANSACTION_AMOUNT, ACCOUNT_ID) VALUES (1, 10000, 1);
INSERT INTO "TRANSACTION" (TRANSACTION_ID, TRANSACTION_AMOUNT, ACCOUNT_ID) VALUES (2, 20000, 1);
INSERT INTO "TRANSACTION" (TRANSACTION_ID, TRANSACTION_AMOUNT, ACCOUNT_ID) VALUES (3, 30000, 2);
INSERT INTO "TRANSACTION" (TRANSACTION_ID, TRANSACTION_AMOUNT, ACCOUNT_ID) VALUES (4, 40000, 2);
INSERT INTO "TRANSACTION" (TRANSACTION_ID, TRANSACTION_AMOUNT, ACCOUNT_ID) VALUES (5, 50000, 3);
INSERT INTO "TRANSACTION" (TRANSACTION_ID, TRANSACTION_AMOUNT, ACCOUNT_ID) VALUES (6, 60000, 3);